# Generated by Django 4.1.7 on 2023-04-16 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    msg = "Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed."
    re = '^\\+?0?\\d{9,15}$'
    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17,
                                                  validators=[django.core.validators.RegexValidator(message=msg,
                                                                                                    regex=re)])),
                ('city', models.CharField(max_length=30)),
                ('account_type', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'),
                                                           ('B', 'Teacher and Student')], default='S', max_length=1)),
                ('meeting_method', models.CharField(choices=[('L', 'Live'), ('O', 'Online'),
                                                             ('B', 'Live and Online')], default='B', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
