# Generated by Django 4.2 on 2023-05-03 15:08

import django.core.validators
from django.db import migrations, models

msg = "Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed."
reg = '^\\+?0?\\d{9,15}$'


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True,
                                   validators=[django.core.validators.RegexValidator(message=msg, regex=reg)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.TextField(blank=True, max_length=100, null=True,
                                   validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
