# Generated by Django 4.2 on 2023-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_profile_profession'),
        ('users', '0003_add_users_test'),
    ]

    operations = [
    ]
