# Generated by Django 4.1.7 on 2023-04-17 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_bio_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourses',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('years_of_experience', models.IntegerField(choices=[(0, '0'), (1, '1'),
                                                                     (2, '2'), (3, '3'),
                                                                     (4, '4'), (5, '5+')], default=0)),
                ('difficulty_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'),
                                                               ('A', 'Advanced')], max_length=30)),
                ('category', models.CharField(choices=[('BUSINESS_AND_MANAGEMENT', 'Business & Management'),
                                                       ('COMPUTER_SCIENCE_AND_IT', 'Computer Science & IT'),
                                                       ('CREATIVE_ARTS', 'Creative Arts'),
                                                       ('ECONOMICS', 'Economics'),
                                                       ('HISTORY', 'History'),
                                                       ('HEALTH_AND_PSYCHOLOGY', 'Health & Psychology'),
                                                       ('LITERATURE', 'Literature'),
                                                       ('LAW', 'Law'),
                                                       ('LANGUAGES_AND_CULTURES', 'Languages & Cultures'),
                                                       ('MATHS', 'Maths'), ('MARKETING', 'Marketing'),
                                                       ('OTHER', 'Other'),
                                                       ('POLITICS_AND_SOCIETY', 'Politics & Society'),
                                                       ('SCIENCE_AND_ENGINEERING', 'Science & Engineering'),
                                                       ('SPORT_AND_LEISURE', 'Sport & Leisure')], max_length=30)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Teacher Courses',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5),
                                                           django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='course.teachercourses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
