# Generated by Django 4.2 on 2023-05-06 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_studentcourses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherCourses',
            new_name='TeacherCourse',
        ),
    ]
