# Generated by Django 4.2 on 2023-05-08 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('chat', '0002_message_group_message_sender_message_student_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_studentcourses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourses',
            new_name='StudentCourse',
        ),
        migrations.RenameModel(
            old_name='TeacherCourses',
            new_name='TeacherCourse',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='student_id',
            new_name='student',
        ),
    ]
