# Generated by Django 4.2 on 2023-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_studentcourses_studentcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'),
                                            ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
