# Generated by Django 4.2 on 2023-05-06 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_group_message_sender_message_student_course_and_more'),
        ('course', '0004_rename_teachercourses_teachercourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourses',
            new_name='StudentCourse',
        ),
    ]
