# Generated by Django 4.2 on 2023-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
