# Generated by Django 4.1.7 on 2023-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'),
                                                        (4, 'Four Stars'), (5, 'Five Stars')])),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
